name: Integración Continua Nivel 5

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código fuente
      uses: actions/checkout@v4

    - name: Instalar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Paso C: Restauramos solo API y Tests para evitar el error de MAUI/Android
    - name: Restaurar dependencias
      run: |
        dotnet restore GestionITM.API/GestionITM.API.csproj
        dotnet restore GestionITM.Test/GestionITM.Test.csproj

    # Paso D: Compilamos específicamente el Backend
    - name: Compilar Backend y Tests
      run: |
        dotnet build GestionITM.API/GestionITM.API.csproj --configuration Release --no-restore
        dotnet build GestionITM.Test/GestionITM.Test.csproj --configuration Release --no-restore

    # Paso E: Ejecutamos las pruebas de xUnit de Daniel
    - name: Ejecutar pruebas unitarias
      run: dotnet test GestionITM.Test/GestionITM.Test.csproj --configuration Release --no-build --verbosity normal

    # Paso F: Validamos que el Dockerfile de la API sea correcto
    - name: Validar construcción de imagen de Docker
      run: docker build -t gestion-itm-api:latest -f Dockerfile .