name: Integración Continua Nivel 5

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

env:
  # Esto asegura que las acciones de GitHub usen una versión moderna de Node
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código fuente
      uses: actions/checkout@v4

    - name: Instalar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Paso C: Usamos *.slnx para que el robot encuentre la solución automáticamente
    - name: Restaurar dependencias
      run: dotnet restore *.slnx 

    # Paso D: Compilamos en modo Release para asegurar que todo el código es válido
    - name: Compilar código
      run: dotnet build *.slnx --configuration Release --no-restore

    # Paso E: Ejecutamos los tests de xUnit que preparó Daniel
    - name: Ejecutar pruebas unitarias
      run: dotnet test *.slnx --configuration Release --no-build --verbosity normal

    # Paso F: Validamos que el Dockerfile que ya probamos en local también funcione en la nube
    - name: Validar construcción de imagen de Docker
      run: docker build -t gestion-itm-api:latest -f Dockerfile .